## test for 03-express-db

# name: CI/CD pipeline

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20

#       - name: Install dependencies
#         working-directory: 03-express-db
#         run: yarn && yarn prisma generate

#       - name: Run tests
#         working-directory: 03-express-db
#         run: yarn run test

## test for 04-integration-test
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure Docker Compose is available
        run: docker compose version

      - name: Copy .env.example to .env
        run: cp ./04-integration-test/.env.example ./04-integration-test/.env

      - name: Run integration script
        run: cd 04-integration-test && yarn run test:integration
